#ifndef UI_H_INCLUDED
#define UI_H_INCLUDED
enum DOS_COLORS {
    BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, BROWN,
    LIGHT_GRAY, DARK_GRAY, LIGHT_BLUE, LIGHT_GREEN, LIGHT_CYAN,
    LIGHT_RED, LIGHT_MAGENTA, YELLOW, WHITE
};
void textcolor (DOS_COLORS iColor);

#endif // UI_H_INCLUDED
